### ISSUE TITLE
Searching for edge

### ISSUE THREAD

**Issue by tmmurali** [Murali-group/GraphSpace#103]
I am searching in http://graphspace.org/graphs/user1%40example.com/KEGG-Wnt-signaling-pathway/?layout=manual-top-to-bottom

How can I find the edge BAMBI -> LRP6,LRP5 using an exact search? The user will have that expectation because she can see that edge.

**Comment by adbharadwaj** [comment]
If a user searches for `BAMBI::LRP6,LRP5`. GraphSpace will search for edge between BAMBI and LRP6 and a node LRP5. Since comma is a special token in our search semantics. This scenario is unavoidable.
