### ISSUE TITLE
Poor visual cues for navigation when screen area is small

### ISSUE THREAD

**Issue by ategge** [Murali-group/GraphSpace#104]
When I first logged into graphspace, and the screen was not maximized, I noticed that the black header bar does not display all options. Instead, a condensed version is used. Upon logging in, I did not know what to do. Clicking the GraphSpace link took me nowhere. I eventually realized that the Graphs word had a link, and that link took me to the graphs page. I understand that as the screen size shrinks, there is not enough space to display all the information. However, without the graphs/groups/help buttons, a novice user might get confused. Perhaps an alternative would be to condense the login portion of the header and keep the graphs/groups/help buttons available for the user.

![screen shot 2015-07-09 at 1 37 07 pm](https://cloud.githubusercontent.com/assets/11236417/8602326/c6d1add6-263f-11e5-8a85-83d0cbf5ca1b.png)

**Comment by adbharadwaj** [comment]
- Burger icon is the standard icon for mobile interfaces. Using any other icon will be against the rules of consistency in UX design.
- However, we have added buttons and hyperlinks to the home screen to provide ample visual cues to GraphSpace features.

![image](https://cloud.githubusercontent.com/assets/3481095/25319038/18045a3e-2867-11e7-86fe-21e4f5ca21d1.png)
