### ISSUE TITLE
No popup when deleting graphs

### ISSUE THREAD

**Issue by ategge** [Murali-group/GraphSpace#105]
Now that #71 has been implemented, there is no popup to alert a user they are deleting a graph. This is dangerous since the command is irreversible. Can we have a popup notification added when a user tries to delete a graph through the GUI?

**Comment by ategge** [comment]
I just deleted graphs from GraphSpace and no confirmations were asked prior to deleting the graphs. Did this functionality stop working?

**Comment by adbharadwaj** [comment]
This issue doesnt seems to exist in GraphSpace 2.0.
