### ISSUE TITLE
no graph displayed for some values of k filter

### ISSUE THREAD

**Issue by ategge** [Murali-group/GraphSpace#112]
We had discussed in email previously, but I will file an issue so we do not forget, that when certain values of the k-filter are used (in the case below k <=20), no graph is displayed.

http://graphspace.org/graphs/ategge%40vt.edu/HIF1-Neurotrophin-k250/

I just talked this through with Divit in person to demonstrate the bug.

**Comment by tmmurali** [comment]
This issue seems to have gone away. Allison, can you confirm and close the bug?

**Comment by ategge** [comment]
Seems to be fixed. Granted, this bug was very hard to catch!
