### ISSUE TITLE
When uploading a JSON graph through the user interface, it is unclear what the "Title of Graph" means

### ISSUE THREAD

**Issue by annaritz** [Murali-group/GraphSpace#115]
I uploaded a graph using the "Upload New Graph" button.  I assumed that entering text into the "Title of Graph" box will cause the graph title to be the text string.  Instead, what I type in is included in the URL (it's the graph ID, I believe).  The graph title is still listed in the JSON file that is uploaded.  

To test this I uploaded example.json that is included in the Help section (and also in the Git repo).

**Comment by adbharadwaj** [comment]
Closing this issue since it has been made clear in latest documentation. 

http://manual.graphspace.org/en/latest/GraphSpace_Network_Model.html?highlight=title#graph-data-attributes-attributes-treated-specially-by-graphspace

**Comment by tmmurali** [comment]
Looks like some of the pages linked from this part of the documentation do
not exist yet. I visited
http://manual.graphspace.org/Viewing_Graphs.html#graph-visualization-tab
for example.
