### ISSUE TITLE
Search remains persistent when the user has a different intention

### ISSUE THREAD

**Issue by tmmurali** [Murali-group/GraphSpace#117]
I visited http://graphspace.org/graphs/ategge@vt.edu/27360-89-0:Bisphenol-A-NCIPID-edges?layout=Final_layout&layout_owner=ategge@vt.edu

I used "MAPK" as a search term. The correct nodes received a blue border.

Next, I manually erased "MAPK" in the search box and typed in "FOXO". While the nodes with "FOXO" in them did get a blue border, the nodes matching "MAPK" did not lose their blue border. 

However, the link to the graph with distinguished elements did point to http://graphspace.org/graphs/ategge@vt.edu/27360-89-0:Bisphenol-A-NCIPID-edges?layout=Final_layout&partial_search=FOX,

That is, "MAPK" did not appear in the URL. So the URL is correct (after adding the layout_owner to the URL, which is a different issue) but the visual results of the search are incorrect.

**Comment by mishravikas** [comment]
@tmmurali adding back the line https://github.com/Murali-group/GraphSpace/blob/master/graphs/static/graphs/js/view_graph.js#L519  fixes this issue. Any reason for it being commented out?

**Comment by DSin52** [comment]
The reason that it is commented out is because if there is a filter applied to the graph (Step through Filtering)  and the user clicks "Clear Search", then any filter that is currently applied gets cleared as well.

**Comment by tmmurali** [comment]
Can we fix the bug by deleting only the CSS elements relevant to the search?
   Murali

**Comment by mishravikas** [comment]
@tmmurali I'm looking for possible solutions and will send a pr as soon as I have it.

**Comment by mishravikas** [comment]
@DSin52 @tmmurali Is Step-Filter already implemented? I couldn't find anything about it in the source code?

**Comment by tmmurali** [comment]
Depends on exactly what you are looking for. For graphs that have an
integer valued rank (or is it "r"?) attribute, the GraphSpace interface
when a user views the graph will contain a panel called "Filter paths". See
http://graphspace.org/graphs/annaritz@vt.edu/NetPath-TCR-pathlinker-top200paths
for example.

The user can move the bars around to control the number of paths shown. I
don't know where the code is.
