### ISSUE TITLE
Incorrect curl command to share graph with a group does not return an error message

### ISSUE THREAD

**Issue by jlaw9** [Murali-group/GraphSpace#118]
According to the graphspace help, the curl command to share a graph with a group is:

  curl -X POST "http://graphspace.org/api/users/graphs/[graph name]/share/[group_owner]/[group name]/" -F "username=[email]" -F "password=[password]"; echo

If either the [group_owner] or [group_name] is incorrect, the curl command still returns the message "Graph successfully shared with group!" with a status code of 200. 

A more helpful message would be something like: "jeffl@vt.edu does not own that group", or "Group name does not exist"

**Comment by tmmurali** [comment]
Good point. In general, how does the programmer know whether the request
was successful or not? Does the documentation contain all the possible
errors or success codes for each curl command?

**Comment by DSin52** [comment]
Thanks @jlaw9 for making this an issue on GitHub.. I really like leaving a trail of progress throughout the development of GraphSpace.  I have added an error that notifies the user if the group they are trying to share graph with does not exist.  @tmmurali I tried to add error checking for the curl commands, I guess I just overlooked this error.

**Comment by tmmurali** [comment]
Thanks. Do you also check if the group exists but the user is not the
owner? Will this error trigger a different message?

Divit, can you also answer "Does the documentation contain all the possible
errors or success codes for each curl command?"

**Comment by DSin52** [comment]
No, I do not check for that error currently.  No, the documentation does not contain all the possible errors or success codes.  Instead, all of the curl commands follow a pattern: If there is an error thrown, there will be an "Error" property as part of the payload, otherwise there will be no "Error" key.  There is currently no exhaustive list of errors that GS can throw.

**Comment by tmmurali** [comment]
You should check for this error as well. Let us come up with a list of
possible errors in a group meeting and then plan how to write the code.

**Comment by tmmurali** [comment]
@jlaw9 can you check if we can close this bug?

**Comment by jlaw9** [comment]
Now if either the [group_owner] or [group_name] is incorrect, the curl command returns the message "Group does not exist" with a status code of 400.

I think that's good enough to close this bug
