### ISSUE TITLE
Search on tags is not intuitive

### ISSUE THREAD

**Issue by ategge** [Murali-group/GraphSpace#120]
I used the tags search and typed in "fun" in hopes to find the tag "Funtion Linkage network" (I just now noticed my mispelling of Function, but that does not negate this issue). However, no tags show up. In order for tags search to work, a user needs to know the entire name of a tag. Can this be a search similar to the graph search where we can query partial tag names to see which tags match the search?

Moreover, when no graphs are found that meet the search criteria, I receive the following message:

"It appears that you currently have no graphs uploaded that match the search terms. Please create an account and join a group or upload your own graphs through the REST API or web interface with the given search criteria in order to see them here."

It makes no sense to instruct me to create an account when I am already logged into GS. Plus, it is unclear what it means to upload graphs "with the given search criteria."

**Comment by adbharadwaj** [comment]
GraphSpace now allows substring search on tags. Please refer to the [docs](http://manual.graphspace.org/en/latest/Searching_Graphs.html) for further details.
