### ISSUE TITLE
"Graph Name" is ambiguous: could refer to Graph Title or Graph ID

### ISSUE THREAD

**Issue by annaritz** [Murali-group/GraphSpace#121]
The word "name" is ambiguous, since it may refer to the graph ID or the text that appears in the title. It currently corresponds to the text in the title in the JSON file, but the phrase "graph name" is used in the Help section to refer to graph ID. I suggest the following:

1. Rename "name" attribute to "title" in the JSON metadata.
2. In the Help sections, convert "graph name" to "graph ID" (or "unique graph ID").  When referring to the title of the graph, call it "graph title".

**Comment by Pratik151** [comment]
@DSin52  @annaritz 
I think this issue can be closed as this was already fixed [here](https://github.com/Murali-group/GraphSpace/commit/29d4ce2606922d47d4448b0534c6e640ecc54991)
