### ISSUE TITLE
Typo in "Something went wrong" message

### ISSUE THREAD

**Issue by annaritz** [Murali-group/GraphSpace#123]
In the message "Oops, Something went wrong! Admin has contacted..." you're missing a "been:"

Admin has **been** contacted.

**Comment by tmmurali** [comment]
Even better: "The GraphSpace administrators have been notified."

Anna, what happened to trigger this message? What you mention in the next
bug report?

**Comment by annaritz** [comment]
I do not know - one of my students pointed out the typo, but didn't explain precisely what caused it.  He was trying to post large graphs to GraphSpace (~1,000 nodes) and Cytoscape.js was having a hard time rendering it.
