### ISSUE TITLE
Unauthorized user is able to delete ANY graph owned by ANYONE

### ISSUE THREAD

**Issue by mishravikas** [Murali-group/GraphSpace#132]
It is possible to delete any graph without being authenticated by using simple curl requests:
Suppose I want to delete the graph
http://graphspace.org/graphs/user1@example.com/KEGG-Prolactin-signaling-pathway

All I need to do is use the following CURL command:
curl -X POST "http://graphspace.org/deleteGraph/"  -F "gid=KEGG-Prolactin-signaling-pathway" -F "uid=user1@example.com"

*I didn't run the above command because the above graph is referenced in some other issues hence didn't want to delete it, tried it in my local copy and it worked.

@tmmurali

**Comment by MridulS** [comment]
@mishravikas Yeah this is a serious bug. All views  `deleteLayout`, `makeLayoutPublic`, `getGroupsForGraph`, `deleteGraph` ...... should be protected, there is no authentication check right now.

@DSin52

**Comment by mishravikas** [comment]
@MridulS Yeah I've stopped creating issues for new views now and have already added authentication check for deletion and viewing json and will be sending a pr soon.  I also found issues in group implementation, any user can create a new group and use a curl command to give access to that graph.

I think it would be better to look at Groups and permissions implementation on a more deeper level instead of just adding a check on every view.

@tmmurali  @DSin52 Any thoughts?

**Comment by tmmurali** [comment]
Thank you for opening these issues. After seeing your messages, I agree
that we may need to examine groups and permissions from the ground up.

Divit, your thoughts?
   Murali

**Comment by DSin52** [comment]
I agree.  I believe the reason that the above commands didn't have any permissions checking was that those specific routes were traditionally only passed from the web application and not the REST API.  Once the user was logged in, I just used the uid (logged in user) token since Django automatically sets that.  Thank you for noticing this and yes there should have definitely been some authentication step.

**Comment by mishravikas** [comment]
@DSin52 @tmmurali Should only the owner be allowed to delete the graph or any member of the group with which the graph is shared can delete it?
Same question goes for other administrative actions like change layout name, make layout public, etc.

**Comment by tmmurali** [comment]
Yes, only the owner should be allowed to delete the graph.

Each layout is owned by the user who created it. Such a user could be the
owner of the graph or a person with whom the graph is shared. Only the
owner of a layout should be allowed to change its name or delete it or make
it shared with others in the group.

**Comment by DSin52** [comment]
I added in the authentication checks for the above routes by utilizing the user session instead of passing the "uid" around with requests.  Thank you guys for pointing this out.  As far as reset password without any authentication, I haven't figured out my plan of attack just yet.

**Comment by adbharadwaj** [comment]
I have added authentication checks to all CRUD operations in graphspace. This issue is solved in GraphSpace 2.0
