### ISSUE TITLE
Unauthorised user is able to change layout name for private layouts of any graph

### ISSUE THREAD

**Issue by mishravikas** [Murali-group/GraphSpace#133]
This is similar to #132. Here a simple CURL command can be used to change the layout name. This can be checked using the following format of the CURL command.
curl -X POST "http://localhost:8000/changeLayoutName" -F "new_layout_name=[NEW_LAYOUT_NAME_HERE]" -F "gid=[GRAPH_ID]" -F "loggedIn=[OWNER_OF_LAYOUT]" -F "old_layout_name=[OLD_LAYOUT_NAME]" -F "uid=[OWNER_OF_LAYOUT]"

@tmmurali

**Comment by DSin52** [comment]
This issue is now resolved.  I now use user session that django provides when someone signs into GraphSpace.
