### ISSUE TITLE
Create edge with non-existent node(s).

### ISSUE THREAD

**Issue by MridulS** [Murali-group/GraphSpace#134]
Currently we can create an edge with nodes not described in the nodes list of JSON. It will create an entry in the db but won't reflect in the visualisation of graph. The solution could be: we raise an error if there exists an edge between non-existent node(s) or we add node(s) with no(minimal) data associated with them.
@DSin52 @tmmurali

**Comment by tmmurali** [comment]
Do you mean that the JSON can contain an edge without the nodes also being
in the JSON? If that is the case, we should raise an error and reject the
graph while also providing the reason.

We have a script called graphspace_interface.py that includes a JSON
validator that should catch these errors. It seems like we should invoke
this validator (it is in Python, though) in the GraphSpace interface
whenever someone uploads a graph. Divit, what do we do currently?

**Comment by MridulS** [comment]
@tmmurali  I think we should add a check for this in `validate_edge_properties` inside `json_validator.py`

BTW This is in the comments of graphspce_interface.py :smile:
```

#Divit's Note: We should have a JSON validator at this step
#Divit: We should.  I want to talk to Murali about possibly enhancing the validator.
```

We use networkx in graphspce_interface.py to create a graph and it will create an edge with non-existent nodes, by adding nodes. So probably enhancing the `json_validator.py` is something we should look into.

@DSin52 thoughts?

**Comment by tmmurali** [comment]
Let me also get into the habit of using @ signs.

@DSin52, what do you think?
   Murali

**Comment by MridulS** [comment]
https://github.com/Murali-group/GraphSpace/pull/142

**Comment by DSin52** [comment]
I think that this is a very reasonable request.  We have to be careful to update both the json validator in graphspace_interface.py and in GraphSpace to make sure they are 100% consistent.
