### ISSUE TITLE
Anyone can reset password for any user without any authentication

### ISSUE THREAD

**Issue by mishravikas** [Murali-group/GraphSpace#137]
It is possible to change password for any user using a CURL command.
This bug is similar to #131 #132 #133 but creating this one separately since its a very serious issue and am taking this one on priority. 
@tmmurali @MridulS

**Comment by MridulS** [comment]
@mishravikas @DSin52 @tmmurali Maybe we should probably revisit the authentication and views model again.

**Comment by mishravikas** [comment]
@MridulS Exactly my thoughts, we should definitely revisit authentication model.
According to the current model, there's no proper way to fix this issue, or for the fact of the matter no issues relating to authenticated users since the current authentication model creates a context object 'session'[1] when you login and it embeds a 'uid' [2] in the page which is then retrieved using jquery [3] and passed on to views where it is used to check which user is authenticated. Now the problem with this is that any person who has basic knowledge of developer tools in a browser can use inspect element and edit the 'uid' tag to replace it with his desired username, which effectively makes him authenticated, which is not the case. 

Even if we assume that the current model of using 'session' and embedding 'uid' in the page works as intended then,  the issue with the current model is that there's no method which can be used to check whether the user is authenticated or not if 'session' is not present in 'request' which is the case with the CURL requests like in this example, when you make a CURL request to reset password 'request' does not have 'session' object and hence no way of checking whether user is authenticated or not. 

According to me the best way to sort out all these issues is to use Django's default User model which is quite secure and has good support for granular level of permissions and groups, which takes care of issues with groups and permissions. I think this can be a nice GSoC project as well.

@DSin52 @tmmurali Your thoughts and suggestions on this?
[1]https://github.com/Murali-group/GraphSpace/blob/master/graphs/auth/login.py#L23
[2]https://github.com/Murali-group/GraphSpace/blob/master/graphs/templates/graphs/view_graph.html#L202
[3]https://github.com/Murali-group/GraphSpace/blob/master/graphs/static/graphs/js/view_graph.js#L602

**Comment by DSin52** [comment]
Good catch, we definitely can't use the 'session' and 'uid' since we have no way of knowing who the user is.. A possible alternative that I can think of is using follow-up "Secret questions" like many companies use when trying to verify a user.  This seems like a very easy fix to this problem.  We can ask all users to insert some answers to basic questions and that could be a further step for verification before we blindly reset a user's password.  

@mishravikas @MridulS @tmmurali

**Comment by tmmurali** [comment]
I don't see how secret questions can help here if the issue is that a CURL
command can be used to reset the password. @dsin52, can you explain?

@mishravikas <https://github.com/mishravikas> please send Divit and me the
curl command by email.

**Comment by DSin52** [comment]
The reset password functionality has been changed in the following way..

1) If a user resets their password, they may still use the original password if they remember it.  The email will still send to the person, but if they don't go through the process of resetting their password, nothing will change for them.

2) The curl request for resetting the password now includes a code for the person who is trying to reset their password.  This code is generated server-side and only the person who receives the email can see this code.  This code gets automatically populated when the user tries to reset their password through the user interface when they click the link sent to their email.  If anyone tries to make a curl request trying to reset a password, they must know this code ahead of time.
