### ISSUE TITLE
Use local_settings.py to avoid running gs-setup.sh everytime you close the terminal

### ISSUE THREAD

**Issue by mishravikas** [Murali-group/GraphSpace#143]
Currently you have to run gs-setup.sh after you have closed the terminal or after the system reboot since the script creates temporary environment variables which are lost once the terminal is closed.
We can use a local_settings.py which will be added in .gitignore file hence, it will not be public and all the variables which need customization and personal value can reside in that file. Finally local_settings.py can be imported in the settings.py in the end.

This will allow us to run gs-setup.sh only once during the initial setup and simplify the dev workflow.
@tmmurali @DSin52

**Comment by DSin52** [comment]
@mishravikas Thanks for the tip.. I have modified the setup script to use this instead of environment variables.  Using this approach makes the set up process a lot smoother.  I will integrate into the master branch in the near future.
