### ISSUE TITLE
Allow token based authentication in REST API

### ISSUE THREAD

**Issue by mishravikas** [Murali-group/GraphSpace#144]
As pointed out by @tmmurali in the comment https://github.com/Murali-group/GraphSpace/issues/88#issuecomment-110121077  It would help to have support for programmable actions like upload graph, export PNG, etc. The current implementation  of the REST API supports only server based authentication and since the HTTP protocol is stateless, which means that if we authenticate a user with a username and password, then on the next request, our application won’t know who we are. We would have to authenticate again. This would be a hurdle in case of programmable mechanism and is a redundancy which can be removed by using a token based authentication.

@tmmurali @DSin52 Your thoughts?

**Comment by DSin52** [comment]
You're completely right @mishravikas.  There definitely should be a token based authentication system in place.  I will look further into this.

**Comment by adbharadwaj** [comment]
This issue has addressed in GraphSpace 2.0. GraphSpace now uses basic auth for token based auth now.
