### ISSUE TITLE
Remove default layout button does not work

### ISSUE THREAD

**Issue by ategge** [Murali-group/GraphSpace#145]
I can set a saved (and shared) layout to be the default layout. If I click on the remove default layout button, nothing changes. When I re-navigate to the page, I still see the previous default layout.

**Comment by tmmurali** [comment]
Can you give the URL of a graph that exemplifies this bug?

**Comment by ategge** [comment]
Yes. In the following graph I have set layout_2 as the default layout. I tried removing layout_2 as the default layout so there would be no default layout for the graph. This does not remove the default layout. I can, however, switch the default layout to layout_1.

http://graphspace.org/graphs/ategge@vt.edu/LSEC_3D_HLK_d12-full-network-edgethreshold-1e-02

**Comment by DSin52** [comment]
There was some code which I had written which compared the name of the default layout to the layout that currently exists in the layouts table.  If you had changed the names of these layouts, it wouldn't be able to find them.  This is now resolved.  I reference all layouts through their unique ID's (primary key) assigned to them upon creation.  No comparison is needed.

**Comment by ategge** [comment]
The bug of this issue is closed. I just noticed that the same icon is used for setting and removing the same default layout.
