### ISSUE TITLE
Graphs take a long time to upload when overwriting existing graphs in DB

### ISSUE THREAD

**Issue by annaritz** [Murali-group/GraphSpace#147]
When a user posts a graph that exists, it is now taking a few minutes per graph.  If the graph is deleted first (before the user uploads it) then the post is much faster (takes few seconds compared to minutes).  

The users are using my "example-interface.py" code, which does the following:
(1) builds a NetworkX graph using the interface module
(2) uses a curl command to check if a graph exists.
(3a) - If the graph exists, uses a curl command to overwrite the existing graph. (this takes a long time)
(3b) - If the graph doesn't exist, uses a curl command to post a new graph. (this is much faster)

Note, I labeled this as high priority since I have many students using it with final theses/reports due in a few weeks.

I'd be happy to time this if it would be useful.  Thanks! - Anna

**Comment by DSin52** [comment]
@annaritz I just looked through the queries and saw I believe I fixed the issues that were causing the slow-down.  I tried your script using (3a) as the scenario and it seems to be working fairly fast now.  Let me know if you still have issues.
