### ISSUE TITLE
HTML color codes are not checked

### ISSUE THREAD

**Issue by annaritz** [Murali-group/GraphSpace#149]
When an HTML color code is incorrect (e.g., only five digits instead of six, such as #00000), no error is thrown BUT the graph never renders.  It just appears as a blank screen.  

See, for example: http://graphspace.org/graphs/annaritz@vt.edu/badHTML

The graph above has a node colored #00000.

Anna

**Comment by DSin52** [comment]
@annaritz try not to put your password on GitHub since it is open to the public now. I'll look into this right now.

**Comment by annaritz** [comment]
Right, thanks. Password is now changed.  Graphspace has been very slow on my end - I couldn't create a group and share this graph with you, and I didn't add tags so couldn't make it public easily.  These may be connectivity issues, but my students are finding that GS is slow as well.

**Comment by DSin52** [comment]
That's weird.. I'll look into seeing how much traffic we're getting.

**Comment by annaritz** [comment]
Looks like @MridulS has fixed this - @DSin52, are you in charge of merging or can I go ahead and do this?

**Comment by tmmurali** [comment]
@annaritz, @MridulS is adding a function to check if a named colour, e.g., AliceBlue, is legal. Once this fix is in, @DSin52 or @adbharadwaj can accept his pull request.
