### ISSUE TITLE
Metadata tag: is it "title" or "name"?

### ISSUE THREAD

**Issue by annaritz** [Murali-group/GraphSpace#150]
In the programmer's guide, http://graphspace.org/help/programmers, the text at the top of description is called "title" in the JSON example but it's listed as "name" in the table.  This needs to be consistent.  

This issue may be related to #121 with "Graph Name" vs. "graphID".

**Comment by adbharadwaj** [comment]
This issue is fixed the documentation. http://manual.graphspace.org/en/latest/GraphSpace_Network_Model.html
