### ISSUE TITLE
Visibility is "Private" for public graphs

### ISSUE THREAD

**Issue by annaritz** [Murali-group/GraphSpace#151]
I have made all graphs with the "AttributeGallery" tag public:

http://graphspace.org/graphs/public?tags=AttributeGallery

However, the Visibility status is still listed as Private. I also made an individual graph public, but the visibility is still listed as Private.

**Comment by DSin52** [comment]
The fix to this will be up on GraphSpace tonight.  I believe the visibility of the graphs is being set correctly, however, GS isn't showing the proper value in the table of graphs.
