### ISSUE TITLE
Searching for "Wnt" in all graphs returns an error

### ISSUE THREAD

**Issue by annaritz** [Murali-group/GraphSpace#153]
I log into my account, enter "Wnt" in the search box, and hit "Search".  The URL is http://graphspace.org/graphs?partial_search=Wnt 

I get a TypeError (sorry don't know how to make this a block typewriter font):

`TypeError at /graphs
'NoneType' object has no attribute '__getitem__'
Request Method:	GET
Request URL:	http://graphspace.org/graphs?partial_search=Wnt
Django Version:	1.8.7
Exception Type:	TypeError
Exception Value:	
'NoneType' object has no attribute '__getitem__'
Exception Location:	/home/ubuntu/GraphSpace/graphs/util/db.py in get_visibility_of_graph, line 4422
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/home/ubuntu/GraphSpace',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']
Server time:	Fri, 20 May 2016 10:04:25 -0500`

**Comment by annaritz** [comment]
This appears to be an issue when the person searching _owns_ at least some graphs, and perhaps does not have permission to view other graphs.

**Comment by DSin52** [comment]
I believe I have fixed the error.

**Comment by tmmurali** [comment]
@DSin52, can you tell us what was the reason for the bug and how you fixed
it? I do not see a commit message related to this bug. Thanks.

**Comment by DSin52** [comment]
The reason this bug occurs is in models.py, public may be a NULL field.  Thus, when searching for the public property for a graph, this may return a NULL object (Python calls it a None object).  When I reference it in `get_visibility_of_graph` on line 4411, I didn't check to see if public returned is not null.

**Comment by tmmurali** [comment]
Thanks for the explanation.
