### ISSUE TITLE
Can not save manual layout

### ISSUE THREAD

**Issue by xin30hp** [Murali-group/GraphSpace#155]
Save button is missing, only the button of "Use Layout Editor" is there.  Can not save manual layouts outside of the "Layout Editor".

**Comment by tmmurali** [comment]
@DSin52 Can we fix this error by uncommenting line 337 in v=master/graphs/templates/graphs/view_graph.html#L337?

**Comment by DSin52** [comment]
Sure, I just put it back up.

**Comment by tmmurali** [comment]
Thanks. Was the fix what I suggested? I want to know to improve my
understanding of the code.
