### ISSUE TITLE
"Crowd" appears as an option under "Layout" in every graph

### ISSUE THREAD

**Issue by tmmurali** [Murali-group/GraphSpace#156]
In the "Layout" widget for a graph, apart from "Auto" and "Manual", the "Crowd" option also appears, even when a user is not logged in. An example is http://graphspace.org/graphs/annaritz@vt.edu/Wnt-ipa-nmax10-labeled

This option should appear only if any crowd layouts actually exist for the graph. Otherwise, for a vast majority of GraphSpace users, the "Crowd" option is confusing.

**Comment by DSin52** [comment]
Only members/owner of the Crowd_Group owned by you can even see the Crowd tab.  A public user can't see this anymore.  I can change it to showing this option if there are Crowd layouts, however, I'm not too sure as to the visibility of those layouts.  Thoughts? @tmmurali

**Comment by annaritz** [comment]
@DSin52's change seems to have fixed my issues: public graphs no longer have the "Crowd" layout tab, and when I log in I no longer see the "Crowd" tab (I am not a member of the Crowd_Group).  @tmmurali can correct me if I'm wrong, but we are fine with the Crowd tab appearing even if there are no Crowd layouts *as long as the Crowd tab appears only for members in the Crowd_Group*.  I am marking this issue as closed.
