### ISSUE TITLE
Update graphspace_interface.py to allow any group member to share a graph with a group

### ISSUE THREAD

**Issue by jlaw9** [Murali-group/GraphSpace#158]
graphspace_interface.py is currently setup so that only the group owner can share a graph with the group.

I will update the code to fix this issue.

**Comment by tmmurali** [comment]
@jlaw9 Can you check if the updated graphspace_interface.py in the master branch has this functionality?

**Comment by jlaw9** [comment]
@tmmurali the graphspace_interface.py in the master branch does not have this functionality. 

Currently the curl command made by the _constructShareCommand function uses the same user variable for the [group owner] and [email].

curl command:
curl -X POST "http://graphspace.org/api/users/graphs/[graph name]/share/[group_owner]/[group name]/" -F "username=[email]" -F "password=[password]"; echo

I plan to add an optional "group_owner" input variable that will be set to the user variable by default but can also be set to the email of the group_owner. This added functionality will not break code using the current shareGraph function in graphspace_interface.py

**Comment by tmmurali** [comment]
@jlaw9 I assume you mean that you will add an optional parameter to the _constructShareCommand function.

@DSin52 @adbharadwaj @annaritz does the approach suggested by @jlaw9 seem reasonable?

**Comment by jlaw9** [comment]
@tmmurali I mean that I will add an optional parameter to the shareGraph function (in the form of group_owner=''") and a non-optional parameter to the _constructShareCommand function. Then before the shareGraph function calls _constructShareCommand, the group_owner variable will be set to the user variable if group_owner is empty.

**Comment by jlaw9** [comment]
Another comment, the execute function in graphspace_interface.py only prints an error warning if the string "ERROR" is in the curl output. 

The output of a curl command in which the group does not exist is the following:
{
    "Message": "Group does not exist",
    "StatusCode": 400
}

successful share:
{
    "Message": "Graph successfully shared with group!",
    "StatusCode": 200
}

I suggest the shareGraph function check the "StatusCode" of the curl output the same way the postGraph function does and then print the curl command output  if "StatusCode" != 200

**Comment by annaritz** [comment]
The code is currently structured so the curl commands are built using private functions (e.g.,  _constructShareCommand)  and returned as strings, which are then executed in public functions (e.g., shareGraph()).  @tmmurali I agree with @jlaw9's proposed change to add an optional parameter to the public function shareGraph() that will pass a non-optional parameter to the private function _constructShareCommand.  

@jlaw9 also has a good point that the graphspace_interface.py code was written before there were consistent "StatusCode" values, so it simply looks for the string ERROR.  Now that we have standardized error messages, the code should be updated to reflect this.

**Comment by jlaw9** [comment]
@tmmurali I tried to push my commit of the shareGraph change, but I do not have permission. Can you give me permission to push to the GraphSpace repo?

Also, @annaritz do you think we should update the execute function to print the curl output if "StatusCode" != 200 and then remove the sys.exit() (postGraph uses the StatusCode to see if it should post or update an existing graph)? Or should handling error messages be performed by each function running execute such as the shareGraph function?
