### ISSUE TITLE
swap tutorial and user guide tabs on the help page

### ISSUE THREAD

**Issue by ategge** [Murali-group/GraphSpace#160]
It is strange that when I go to graphspace.org/help, I am presented with the second tab and not the first tab at the top. I feel like the tab you want a user to see first should be the first tab.

Additionally, the link graphspace.org/help (which comes from the manuscript) and clicking the help tab at the top of the web page result in different pages.

**Comment by adbharadwaj** [comment]
Help page has been replaced by sphinx documentation. The documentation is managed on different project right now.

https://github.com/adbharadwaj/graphspace-manual
