### ISSUE TITLE
Provide an interface to alert group membersof a new graph shared with the group

### ISSUE THREAD

**Issue by ategge** [Murali-group/GraphSpace#161]
Providing a mechanism where a group member can email a message/alert to all the group members from GS is more seamless than a user going to their own email and emailing everybody.

**Comment by tmmurali** [comment]
We need a general purpose notification mechanism. Can you close this issue
and open another one on notification with a list of features?

@dsin52 has implemented notifications in the past. We have not yet exposed
that functionality. Which branch is it in?
