### ISSUE TITLE
Notification mechanism

### ISSUE THREAD

**Issue by ategge** [Murali-group/GraphSpace#164]
GraphSpace needs a general notification mechanism that directly alerts users of certain tasks/features. 

@tmmurali previously asked: @dsin52 has implemented notifications in the past. We have not yet exposed that functionality. Which branch is it in?

These features may include:
- email a user when they have been added to a group
- allow a group member to email updates or new uploads to all other members of the group. 
- a user can ask a group owner to be added to a group
- general alerts/updates that GS may need to send to all users

Please add more features to the list as you think of them.

**Comment by DSin52** [comment]
The branch which contains the notification system is `graphcrowd`.  This was worked on only during Fall 2015 during Dr. Luther's class.

**Comment by tmmurali** [comment]
@Dsin52, is it possible to extract only the changes for the notification
system into a separate branch? I realise doing so may be tough. Does the
code on GitHub also reflect the changes you must have made to the database?

**Comment by MridulS** [comment]
@tmmurali I guess we can cherry pick those commits. 

https://git-scm.com/docs/git-cherry-pick

**Comment by adbharadwaj** [comment]
Closing this issue. This is similar to #264
