### ISSUE TITLE
Not all tags visible on the page that lists graphs

### ISSUE THREAD

**Issue by tmmurali** [Murali-group/GraphSpace#165]
When I visit http://graphspace.org/graphs/public to view all public graphs, the only tags I see are in the "Tags" panel on the right "pathlinker-all-netpath-pathways" and "2015-npj-sysbio-appl-pathlinker". There are three pages of results. Several graphs on page 1 have other tags (as can seen in the "Tags" column). When I go to page 2 or to page 3, I can see graphs with other tags.

@DSin52 What are the criteria used to decide which tags will appear in the "Tags" panel on the right hand side? A related issue is #120.

**Comment by adbharadwaj** [comment]
This issue is not relevant to GraphSpace 2.0. There is no special search bar for tags anymore.
