### ISSUE TITLE
Update graphspace documentation as per interface_branch changes.

### ISSUE THREAD

**Issue by adbharadwaj** [Murali-group/GraphSpace#167]
Need to add the documentation and close the branch.

**Comment by tmmurali** [comment]
@adbharadwaj, please list all the places where we should document and what we should add as documentation, e.g., what we say in "Feature" should be brief but what we need in "Programmer's Guide" is more elaborate. Do we need something in "User guide"?

**Comment by adbharadwaj** [comment]
We already added the documentation and closed the branch.

Documentation is maintained now maintained via a [different repository](https://github.com/adbharadwaj/graphspace-manual). The instructions to update the documentation is available in the [README](https://github.com/adbharadwaj/graphspace-manual/blob/master/README.md) file.
