### ISSUE TITLE
Selections not working correctly in Layout editor

### ISSUE THREAD

**Issue by tmmurali** [Murali-group/GraphSpace#169]
@DSin52 I logged in as user1@example.com to view http://graphspace.org/graphs/user1@example.com/KEGG-Prolactin-signaling-pathway 

I started using the layout editor. When I chose "Rectangle" from the list of shapes, only one of the rectangles was selected (the smaller one). Similarly, when I chose "Ellipse" not all the ellipses were selected. Moreover, when I just selected the sole background color, I expected all nodes to be selected but only some were selected.

**Comment by jlaw9** [comment]
Duplicate of #195. Closing this issue as there is more discussion there.
