### ISSUE TITLE
Delete unused branches

### ISSUE THREAD

**Issue by tmmurali** [Murali-group/GraphSpace#170]
@adbharadwaj @DSin52 @annaritz @ategge I see several branches that may no longer be active (e.g., allison changes, bug squashing, apache instance). Can we delete those branches? Please reply here. I want @adbharadwaj to do the actual deletion of the branches.

I am opening a new branch for documentation changes.

**Comment by ategge** [comment]
Sure. @adbharadwaj can delete my branch.

**Comment by annaritz** [comment]
Please leave interface_branch. I will use this branch to add a Programmer's Guide for the Graphspace Interace, and will discuss with @adbharadwaj when I do.

**Comment by adbharadwaj** [comment]
@annaritz Documentation is supported via a [different repository](https://github.com/adbharadwaj/graphspace-manual) now. I am going to transfer the ownership to Murali's Organization soon.

Deleted the unused branches.
