### ISSUE TITLE
local_settings.py contains variables related to GraphCrowd

### ISSUE THREAD

**Issue by tmmurali** [Murali-group/GraphSpace#173]
There are several variables in local_settings.py such as AWS_URL, AWSACCESSKEY, and SECRETKEY that are related to GraphCrowd. They should not be exposed in GraphSpace code.

There is also a variable called SECRET_KEY whose purpose is not documented.

**Comment by tmmurali** [comment]
local_settings.py contains a variable called PATH. Does the user need to set it? If no, please remove it.

**Comment by adbharadwaj** [comment]
This file has been replaced by [local.py](https://github.com/Murali-group/GraphSpace/blob/master/graphspace/settings/local.py). The local.py does not contain any sensitive production information. It is available for use in dev environment and as a template for production.py which is ignored from the github project and can never be added to the project.
