### ISSUE TITLE
Improve organisation of graphs/static/graphs/js

### ISSUE THREAD

**Issue by tmmurali** [Murali-group/GraphSpace#177]
I see several Javascript files in **graphs/static/graphs/js**. It is not clear which files are for GraphSpace proper and which are from other JS libraries we have downloaded. Some of the files in there may not be needed at all, e.g., a colour spectrum picker and Voronoi diagram code. We need to organise this directory into sub-directories, one for GraphSpace and one for each external project. Add a README that keeps track of the versions of external projects and their licences. Check with https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses to make sure each licence is compatible with the GPL.

**Comment by adbharadwaj** [comment]
The javascript is organized by pages now. Each page has a separate js file and each page is divided into js modules.
