### ISSUE TITLE
JSON files uploaded without a title through the UI are titled with the timestamp

### ISSUE THREAD

**Issue by annaritz** [Murali-group/GraphSpace#178]
When you upload a JSON file using the UI that doesn't have a "name" attribute in the metadata, the time stamp is used as the Graph Title.  See, for example, 

http://graphspace.org/graphs/annaritz@vt.edu/PathLinker-Wnt-Final

(it is viewable to @tmmurali, @ategge, and @DSin52).  If a JSON file is uploaded without a "name" attribute, then there should be no title present.

**Comment by adbharadwaj** [comment]
Users can no longer upload a graph with no name.
