### ISSUE TITLE
Refactor GS error message handling in graphspace_interface.py 

### ISSUE THREAD

**Issue by annaritz** [Murali-group/GraphSpace#179]
Following up on comment by @jlaw9 from #158: update the error handling to use the "StatusCode" tag in the execute() function.  "StatusCode" is also used in the postGraph() function to determine if the graph exists.  

Another option is to have each function that calls execute (e.g., postGraph(), shareGraph(), deleteGraph()) handle error messages.  This might be messier, but I will think about it and make changes as necessary.

**Comment by jlaw9** [comment]
A temporary fix is to print the output of each executed curl command (i.e., add `print out` to the bottom of the `execute()` function. That way the user can see if posting and/or sharing a graph was successful or not.

**Comment by adbharadwaj** [comment]
This issue is not relevant in GraphSpace 2.0. graphspace_interface has been replaced by [graphspace_python](https://github.com/adbharadwaj/graphspace-python) library. Any issue related to the library should be reported on the graphspace-python project's issues list.
