### ISSUE TITLE
Graphs with '%' in the title are broken

### ISSUE THREAD

**Issue by jlaw9** [Murali-group/GraphSpace#182]
When I tried uploading a graph with '%'  in the title using curl, I got a "400 Bad Request" back html page from the server.

I tried uploading the same graph/title using the upload graph button on graphspace.org. I got the message:
"Graph is now viewable at: http://graphspace.org/graphs/jeffl@vt.edu/Milbemectin_(mixture_of_70%_Milbemcin_A4,_30%_Milbemycin_A3)_34742!"
but when I clicked on it, I got the same "400 Bad Request" html page

Probably not something we need to handle, but maybe we should have a list of characters not allowed in graph titles and group names

**Comment by jlaw9** [comment]
Graphs with square brackets '[' or ']' in the title (i.e., 4,4'-Sulfonylbis[2-(prop-2-en-1-yl)phenol])  cause the curl commands to fail (curl: (3) [globbing] bad range in column XX), but uploading a graph with that title via the browser works fine.

**Comment by adbharadwaj** [comment]
Please see the response in #198 .

**Comment by adbharadwaj** [comment]
![image](https://cloud.githubusercontent.com/assets/3481095/24950072/c0dee440-1f3d-11e7-8f45-db05f1bf9799.png)
