### ISSUE TITLE
Change "Manual" to "Saved" in the Layouts panel

### ISSUE THREAD

**Issue by tmmurali** [Murali-group/GraphSpace#184]
The "Manual" tab in layouts panel in a graph view is misnomer. Its true purpose is for the user to access saved layouts, whether they are created using automatic algorithms, the layout editor, or manual manipulation of node positions. Hence, we should rename this tab to "Saved". We also need to update the screenshots and text in the documentation and the tutorial.

**Comment by adbharadwaj** [comment]
This issue is not relevant to GraphSpace 2.0. Please refer to the [documentation](http://manual.graphspace.org/en/latest/Interacting_with_Graphs.html#change-layout) to learn how to change layout in Graphspace 2.0.
