### ISSUE TITLE
Use the default layout for a graph uploaded by an anonymous user if available.

### ISSUE THREAD

**Issue by adbharadwaj** [Murali-group/GraphSpace#185]

**Comment by tmmurali** [comment]
I think that our policy is not to allow an anonymous user, that is, an user who has not registered to create a default layout. If we make changes to this policy, it must be an explicit decision.

**Comment by adbharadwaj** [comment]
anonymous user is not allowed to create or upload a layout to GraphSpace. They can only upload a graph anonymously.
