### ISSUE TITLE
Unable to delete a private layout of a graph not owned by you

### ISSUE THREAD

**Issue by jlaw9** [Murali-group/GraphSpace#192]
For example, jamogh uploads a graph. jamogh shares the graph with a group I'm a member of. I create a private layout. If I try to delete that private layout, I get the error message 'Layout does not exist!'

Not a big issue, but it's still an issue

**Comment by adbharadwaj** [comment]
This is fixed. Now the user will get an error saying that the user has no access to the given resource.
