### ISSUE TITLE
validate_edge_properties() in graphspace_interface.py not validating edge properties

### ISSUE THREAD

**Issue by jlaw9** [Murali-group/GraphSpace#193]
networkx must have changed or something.
`validate_edge_properties(G)` for loop:
`for edge_id in G.edge:
    check edge properties of G.edge[edge_id]`
`edge_id` is the source and `G.edge[edge_id]` contains a dictionary of targets and the corresponding properties. 

I propose to change this for loop to loop over each source and target pair:
`for source in G.edge: for target in G.edge[source]: validate edge properties of G.edge[source][target]`

I have tested this implementation and it works. I'm now going through the pull request process to submit my fix

**Comment by tmmurali** [comment]
@jlaw9 I am not sure why you are making this change. Can you explain? What do you think has changed in networkx? Can you check with the networkx documentation?

**Comment by jlaw9** [comment]
@tmmurali sorry I should've made it clearer. 

edge properties of the json file were not being validated because the code was checking the list of targets for edge properties rather than the actual edge properties of the edge.

For example, suppose there is an edge from `node1` to `node2` with the property `'target_arrow_shape': 'error'`.
The networkx Graph.edge object would look like this:
`{'node1': {'node2': {'target_arrow_shape': 'error'}}}`.
The code is currently checking if the property `'target_arrow_shape'` is in the `node1` dictionary (i.e. `G.edge['node1']`). If it is, it will validate that the value (`G.edge['node1']['target_arrow_shape']`) is in the list of acceptable arrow shapes (`error` is not so the code should quit with the error message). `target_arrow_shape` would not be in the `node1`, but in the `node2` dictionary (i.e. `G.edge['node1']['node2']`). I'm simply updating the code to correctly validate `G.edge['node1']['node2']['target_arrow_shape']`)

I'm not sure if something changed in networkx, or if this function was just incorrectly implemented in the first place.

**Comment by tmmurali** [comment]
Thanks for the explanation. What bothers me about both the old and the new version is that they assume the data structure for G.edge has a certain format. It is much safer to invoke a NetworkX function that iterates over edges in the graph and checks the appropriate attributes for each edge. That way the validator does not depend on how NetworkX stores a graph internally. Can you check and let me know. @jlaw9 

@annaritz What do you think?

**Comment by jlaw9** [comment]
@tmmurali There are NetworkX functions that iterate over edges and attributes in the graph. For example: `G.edges(data=True)` is used in our graphspace_interface.py [convertNXToDict(G)](https://github.com/Murali-group/GraphSpace/blob/master/graphspace_interface/graphspace_interface.py#L744). We could certainly use that here. 

However, this point brings the other graphspace_interface.py functions into question. The functions to add edge attributes use the `G.edge[source][target]['attr'] = attr` method (for example: [add_edge_line_style()](https://github.com/Murali-group/GraphSpace/blob/master/graphspace_interface/graphspace_interface.py#L633)) 

NetworkX has functions like `set_edge_attributes()` and `get_edge_attributes()` for setting and getting multiple edge attributes at once, but no individual `set_edge_attribue()` and `get_edge_attribute()` functions (see [networkx edge attribute functions](https://networkx.github.io/documentation/networkx-1.10/reference/functions.html#attributes))

According to the networkx [edge attributes documentation](https://networkx.github.io/documentation/networkx-1.10/tutorial/tutorial.html#edge-attributes), `G.edge[source][target]['attr']` seems to be the appropriate way to set and get individual edge attributes.

**Comment by adbharadwaj** [comment]
I think it has nothing to do with networkx's functionality. The implementation of `validate_edge_properties` was wrong in the first place. The reason behind this confusion is the method name [validate_json(G)](https://github.com/Murali-group/GraphSpace/blob/b1a284ed0b503f58b3bc8b83fe8defbc4fa414a3/graphspace_interface/graphspace_interface.py#L91) which calls `validate_edge_properties(G)`. From the method name it appears that G is a python dictionary which follows the JSON format mentioned on Graphspace. But this is not true. G is an networkx object which has to be converted to JSON format mentioned on Graphspace documentation. 

Here is an example of JSON specification in Graphspace:

``` javascript
data: {
    directed: "false",
    id: "RYK-WNT1",
    k: 81,
    line_color: "#01DF01",
    source: "RYK",
    target: "WNT1",
    target_arrow_color: "#01DF01",
    width: 3
}
```

The current code is expecting the networkx to return a dictionary with above mentioned flat JSON format.

But networkx returns a dictionary with following format:

``` javascript
{  
   'RYK':{  
      'WNT1':{  
         'directed':'false',
         'line_color':'#01DF01',
         'width':3,
         'target_arrow_color':'#01DF01'
      }
   }
}
```

I am sure that networkx's dictionary format for edge hasn't changed. My suggestion is that we should change the name of the method `validate_JSON` to `validate_networkx_graph' and update the `validate_edge_properties` method as suggested by Jeff.

**Comment by tmmurali** [comment]
@adbharadwaj @jlaw9 Thanks for the explanation. One of you can go ahead with this change.

How does this code interact with the validator in graphspace_interface.py? It is also incorrectly named as validate_json().

**Comment by adbharadwaj** [comment]
@jlaw9 Are you making the changes ?

**Comment by adbharadwaj** [comment]
@tmmurali 

**validate_edge_properties** is called inside **validate_json** method. Both methods do not return anything. 

**find_property_in_array** method is called inside **validate_edge_properties** method. 

**find_property_in_array** method looks for a required property in the NetworkX object. If the property exists nothing happens else it raises an exception. This exception is then propagated through **validate_edge_properties** and  **validate_json** method and caught in a try and catch clause in the parent method of **validate_json** .

**Comment by jlaw9** [comment]
Yes I made the changes in my fork, I just need to make the pull request now.

**Comment by adbharadwaj** [comment]
This issue is not relevant in GraphSpace 2.0
