### ISSUE TITLE
Layout Stores Node Background Color

### ISSUE THREAD

**Issue by jlaw9** [Murali-group/GraphSpace#194]
On the graph [Lovastatin_20784_color](http://graphspace.org/graphs/jeffl@vt.edu/Lovastatin_20784_color), I tried changing the color of the node "MAP2K1" from green to red. For some reason, the color didn't completely update.
green:
![screenshot from 2016-08-12 11-45-50](https://cloud.githubusercontent.com/assets/7592559/17628650/6c056188-6084-11e6-9af7-64d387dcc774.png)
red:
![screenshot from 2016-08-12 11-50-20](https://cloud.githubusercontent.com/assets/7592559/17628596/2353a170-6084-11e6-8d58-450c04e787a3.png)

I tried recreating the problem by uploading a test graph and changing the same 3 attributes (listed below) of the color of the node from green to red, but it updated just fine so I'm not sure what caused this issue.

Here are the values of the green colored node:
"border_color": "#ff5050", 
"text_outline_color": "#ff5050",
"background_color": "#ff5050", 

for the red:
"border_color": "#86b300",
"text_outline_color": "#86b300",
"background_color": "#86b300",

**Comment by annaritz** [comment]
Hi @jlaw; this might be an issue with the "bubble_effect" function I wrote in the graphspace interface.  Try looking there, and let me know if I can help.

**Comment by jlaw9** [comment]
Thanks for the suggestion @annaritz. I just figured out the problem.

For some reason, when I removed the default layout, the background color of node MAP2K1 changed from green to red. So for whatever reason, the default layout seems to store the background color of the node along with the position

**Comment by tmmurali** [comment]
@jlaw9 Should the bug title be "**Default** layout ..." or is that every layout stores colors as well?

**Comment by jlaw9** [comment]
@tmmurali Every layout I tested stored the color as well.

**Comment by tmmurali** [comment]
Thanks for confirming.

**Comment by adbharadwaj** [comment]
The latest version of GraphSpace allows users to save style information along with node positions as part of layouts. This bug is not relevant anymore.
