### ISSUE TITLE
Node IDs with certain special characters aren't selected by the layout editor

### ISSUE THREAD

**Issue by jlaw9** [Murali-group/GraphSpace#195]
When choosing a color or shape from the layout editor, not all of those nodes are selected if they have certain special characters in the node ID.

**Not selected / Don't work**:  forward slash ('/'), comma (',')
**Selected / Work**: underscore ('_'), hyphen ('-')

For example: Each of the grey nodes that should be selected in the screenshot below have a forward slash ('/') in their ID.

![image](https://cloud.githubusercontent.com/assets/7592559/17714498/10d6720a-63ce-11e6-9e09-b511c88b03f4.png)

**Comment by tmmurali** [comment]
Commas in node ids are also a problem. This might not be a problem with GraphSpace per se but with Cytoscape.js not liking some characters in node ids.

**Comment by tmmurali** [comment]
To follow up to @jlaw9 last line in the issue report, hyphens also work fine.

**Comment by jlaw9** [comment]
Here is an example of commas in node ids
user1@example.com, http://graphspace.org/graphs/user1@example.com/KEGG-Prolactin-signaling-pathway

**Comment by adbharadwaj** [comment]
This issue ceases to exist in GraphSpace 2.0.
