### ISSUE TITLE
"color" is not a node attribute

### ISSUE THREAD

**Issue by annaritz** [Murali-group/GraphSpace#196]
The documentation says that "color" is an attribute in the Programmer's Guide: http://graphspace.org/help/programmers

`color: The colour of the nodes's content.`

However, the proper attribute is "background_color".  This is illustrated in the Sample JSON file included further down the page.

**Comment by tmmurali** [comment]
@annaritz Do we need to change just the documentation or the code itself?

**Comment by annaritz** [comment]
@tmmurali just the documentation on the help page.

**Comment by tmmurali** [comment]
Thanks. @annaritz We also have a line for background_color. 

background_color	The background color of the node. It may be the names of colors or hexadecimal values of the colors.

Should we move this text to the line for color or just change color to background_color?

**Comment by annaritz** [comment]
After a more careful read, "content" means the text displayed inside the node. So the color property should change the color of the text - I will check and report back.

**Comment by annaritz** [comment]
Yes that's what it means, so it is technically correct.  To clarify, I propose that we replace the text 

`The colour of the nodes's content`

to

`The colour of the text displayed inside the node`

**Comment by ategge** [comment]
Can we be consistent with our spelling of 'color'? It is a little strange to have the attribute name 'color' and the description include 'colour.'

**Comment by annaritz** [comment]
It didn't bother me too much, but I can see how that is inconsisent.

We would need to change "colour" to "color" then - since "color" is a Cytoscape.js attribute: http://js.cytoscape.org/#style/node-body

**Comment by tmmurali** [comment]
Thanks @annaritz @ategge. I will make these changes.

**Comment by adbharadwaj** [comment]
This issue is not relevant anymore after the release of GraphSpace 2.0. Hence I am closing this issue. GraphSpace 2.0 supports all style properties defined by Cytoscape.js. Please refer to [graphspace network model documentation](http://manual.graphspace.org/en/latest/GraphSpace_Network_Model.html#stylesheet-json-format) for more details.
