### ISSUE TITLE
Document illegal characters for GraphID

### ISSUE THREAD

**Issue by annaritz** [Murali-group/GraphSpace#198]
The graphID (called "graphname" in the [Programmer's Guide](http://graphspace.org/help/programmers) cannot contain **spaces** or **question marks**.  This will introduce a space in the URL.  

I have not thoroughly checked, but I bet that [other characters not allowed in URLs](https://perishablepress.com/stop-using-unsafe-characters-in-urls/) will also be problematic.  
- These should be documented in the Programmer's Guide
- An error message should be thrown when trying to upload a graph through the interface with an illegal character in the graphID.

**Comment by jlaw9** [comment]
@annaritz I also ran into this problem trying to posts graphs with a chemical name as the ID. See Issue #182

**Comment by tmmurali** [comment]
@jlaw9 @annaritz Can one of you mark one of the issues as a duplicate? Thanks.

**Comment by adbharadwaj** [comment]
- GraphSpace doesn't allow users to add graph ids anymore. We create a integer ID for each graph on creation. 
- Users can use any character supported by UTF-8 character set for a string field like `name` of the graph.
