### ISSUE TITLE
Illegal characters in password?

### ISSUE THREAD

**Issue by annaritz** [Murali-group/GraphSpace#199]
Someone used a password generator, and the password caused some GraphSpace errors.  I don't know what those errors were, but are there any characters that are not allowed in the password?

**Comment by adbharadwaj** [comment]
@annaritz Do you know the size of password fed by the password generators ? Can you give some examples ?

Mitch, I was talking about these [validators](http://docs.sqlalchemy.org/en/rel_0_9/orm/mapped_attributes.html#simple-validators).

**Comment by annaritz** [comment]
Sorry, I don't know, unfortunately.  If a student has the same issue I'll let you know more details.

**Comment by Anirbanbhk88** [comment]
Hello @jahandaniyal @adbharadwaj @annaritz 
I had used several password combinations for the passwords generated by an online password generator(https://passwordsgenerator.net/) to check their vailidity. I came up with the following obvservations:
1) Password of length 16 characters and including A-Z,a-z, special characters( e.g. @#$% ), 
numbers( e.g. 123456 ), Excluding Similar Characters:( e.g. i, l, 1, L, o, 0, O ), Exclude Ambiguous Characters:( { } [ ] ( ) / \ ' " ` ~ , ; : . < > )
password used: **r6UR566/-S9(5;XH**

**Comment by adbharadwaj** [comment]
This is very helpful. Thanks, @Anirbanbhk88. @annaritz I am going to close this issue for now. Let me know if you find an edge case.
