### ISSUE TITLE
Attribute "mid_source_arrow_shape" requires "source_arrow_shape" attribute to be set

### ISSUE THREAD

**Issue by annaritz** [Murali-group/GraphSpace#200]
The attribute "mid_source_arrow_shape" places an arrow in the middle of the edge, pointing towards the source.  The "mid_target_arrow_shape" places an arrow in the middle of the edge, pointing towards the target.

First, the documentation in the [Programmer's Guide](http://graphspace.org/help/programmers) duplicates the descriptions for "target_arrow_shape" and "mid_target_arrow_shape" (as well as other "target" vs. "mid_target" attributes).  The mid_target descriptions should be clarified.

Next, there is asymmetry in the JSON validator. The following JSON, which uses the "mid_target_arrow_shape" attribute, loads with no problem:

```
{
    "graph": {
        "nodes": [{"data":{"id":"B","content": "B"}}, {"data":{"id":"A","content": "A"}}],
        "edges": [{"data": {
                    "source": "A",
                    "target": "B",
                    "mid_target_arrow_shape":"triangle"
                }}]

    },
    "metadata": {"title": "Graph Name","description": "","tags": []}
}
```

However, the same JSON with "mid_source_arrow_shape" attribute throws a "source_arrow_shape" attribute error.  

```
{
    "graph": {
        "nodes": [{"data":{"id":"B","content": "B"}}, {"data":{"id":"A","content": "A"}}],
        "edges": [{"data": {
                    "source": "A",
                    "target": "B",
                    "mid_source_arrow_shape":"triangle"
                }}]

    },
    "metadata": {"title": "Graph Name","description": "","tags": []}
}
```

I do not know if this asymmetry is due to Cytoscape.js or our JSON validator.

**Comment by adbharadwaj** [comment]
GraphSpace doesn't use `mid_source_arrow_shape` or `source_arrow_shape` data attribute anymore. The style information is supported via [Style attributes](http://manual.graphspace.org/en/latest/GraphSpace_Network_Model.html#style-properties) now. The compatibility of these attributes will completely depend on Cytoscape.js support.
