### ISSUE TITLE
Search on graphpage not working on Firefox

### ISSUE THREAD

**Issue by adbharadwaj** [Murali-group/GraphSpace#233]
Used a firefox browser.

- http://52.38.106.43/graphs/17003#graph_visualization_tab
- Query: PIK3CG

**Comment by adbharadwaj** [comment]
@amoghpj Can you test this URL and see if the search still doesn't work.

**Comment by amoghpj** [comment]
This still doesn't work. Other queries don't work either.

**Comment by adbharadwaj** [comment]
The problem is that there is no node or edge in the node/edge table for this graph. 
**Solution** - Run a migration script which checks for such instances and creates edge and node entries based on graph json.
