### ISSUE TITLE
forgot password feature doesn’t do anything when typing in associated email.

### ISSUE THREAD

**Issue by adbharadwaj** [Murali-group/GraphSpace#236]

**Comment by adbharadwaj** [comment]
I think it is because the email server was not setup.

**Comment by adbharadwaj** [comment]
This feature is working. It required a fix in SMTP server configuration. Hence no commit is attached to this pull request.

**Comment by tmmurali** [comment]
@adbharadwaj Have you documented how to set up the SMTP server in the installation instructions? If not, please add this information.
