### ISSUE TITLE
Layout Editor Node Selection

### ISSUE THREAD

**Issue by jlaw9** [Murali-group/GraphSpace#255]
When selecting colors and node shapes using the layout editor, the selected colors and shapes are applied separately when they selection criteria should be applied together. For example, when trying to select all gray circles, all gray nodes and all circles are selected instead (see screenshot)

![image](https://cloud.githubusercontent.com/assets/7592559/24471488/3b48e28e-1490-11e7-8f5f-9b440f0d6382.png)

**Comment by adbharadwaj** [comment]
Thanks @jlaw9. I have fixed the node selection logic. So if a user selects ellipse and grey color, it should select grey ellipse shaped nodes only.

**Comment by jlaw9** [comment]
Thanks @adbharadwaj!
