### ISSUE TITLE
Unable to change color for text, border, and bubble 

### ISSUE THREAD

**Issue by jlaw9** [Murali-group/GraphSpace#256]
Changing the node background works well, but I am unable to change the other colors in the node such as the node border, text, and the text border or "bubble" around the text. In the screenshot, the nodes were purple and I changed the color to neon green

![image](https://cloud.githubusercontent.com/assets/7592559/24471823/633a446c-1491-11e7-9d9c-a54ab430ac68.png)

**Comment by adbharadwaj** [comment]
It was because text-outline-color and node background color are supported via different properties in Cytoscape.js. I have fixed this issue by changing both of them when a user changes the background of a node. Making sure that background color and text outline color is always matching.
