### ISSUE TITLE
Get graphs by tags via REST APIs

### ISSUE THREAD

**Issue by rishabhsethi** [Murali-group/GraphSpace#259]
The REST API currently doesn't have a method to get all graphs with a particular tag. This seems like an important use case.

**Comment by adbharadwaj** [comment]
This feature is already supported. Please refer to http://manual.graphspace.org/en/latest/Programmers_Guide.html for more details.

**Comment by rishabhsethi** [comment]
Thanks for the clarification. I looked at the code and it seems like [urls.py](https://github.com/Murali-group/GraphSpace/blob/master/graphs/urls.py) is missing the endpoint for the [get_all_graphs_for_tags](https://github.com/Murali-group/GraphSpace/blob/master/graphs/views.py#L2513) method.

**Comment by rishabhsethi** [comment]
I realize I was looking at the master branch instead of the current development branch. Please keep the issue closed.
