### ISSUE TITLE
Problem with PNG and JPG export 

### ISSUE THREAD

**Issue by jlaw9** [Murali-group/GraphSpace#260]
Exporting to PNG or JPG normally works, but when I try to export this graph ([http://35.163.136.54/graphs/21333](http://35.163.136.54/graphs/21333)) to PNG or JPG by clicking on the "Network Graphics" options of export, nothing happens. Exporting to CYJS or JSON works fine. 

I'm wondering if it's because of the large 200x200 nodes?

**Comment by adbharadwaj** [comment]
This is a problem with using href attributes to download files. I used the solution given in this post (via Blobs in Javascript).

http://stackoverflow.com/questions/23301467/javascript-exporting-large-text-csv-file-crashes-google-chrome
