### ISSUE TITLE
Unable to save layout outside of "Layout Editor" mode

### ISSUE THREAD

**Issue by jlaw9** [Murali-group/GraphSpace#262]
If I change the filter, use a layout algorithm or move node positions around, I cannot save the layout unless I click on "Use Layout Editor." Even then, the only way to save a layout is to click on "Exit Layout Editor". I'm not sure why I didn't notice this earlier. 

Can we add a save layout button to the main and Layout Editor modes to be able to save a layout from anywhere?

**Comment by adbharadwaj** [comment]
@jlaw9 Providing `save layout button` in multiple places might confuse a lot users. We want the users to use the layout editor as the only option to save layout. We want to separate the exploration mode (when a user explores the graph details) from editing mode (when  a user changes the graph visual styles).

You also raised a valid point about `Exit Layout Editor` button. I think we can add a `save layout` button to the layout editor and keep the existing functionality on exit layout editor button.
