### ISSUE TITLE
Write up a tutorial on how to use GraphSpace RESTful APIs.

### ISSUE THREAD

**Issue by adbharadwaj** [Murali-group/GraphSpace#270]
@sandeepm96 

- Introduction to GraphSpace REST APIs.
- Introduction to Postman and installation steps.
- Explain how to use Postman for `/graphs` endpoint for GET, POST, PUT.
- Find out how to export a Postman collection and share with public. Are there security concerns for sharing a postman collection?

**Comment by adbharadwaj** [comment]
@sandeepm96 can you add links to the tutorial here ?

**Comment by sandeepm96** [comment]
Here is the link for the tutorial of using GraphSpace REST API: [https://summerofcode17.wordpress.com/2017/05/30/using-the-graphspace-restful-api/](https://summerofcode17.wordpress.com/2017/05/30/using-the-graphspace-restful-api/)

**Comment by tmmurali** [comment]
The tutorial looks very good. Once it is finalised (if it is not yet
completed), can we move it to some location on manual.graphspace.org?

On Fri, Aug 18, 2017 at 1:53 PM, Sandeep Mahapatra <notifications@github.com

**Comment by sanket0211** [comment]
#332

**Comment by sanket0211** [comment]
Similar to #332.

**Comment by adbharadwaj** [comment]
Closing since its a duplicate issue. 
Duplicate of #332
