### ISSUE TITLE
View name of the group with which a graph is shared

### ISSUE THREAD

**Issue by tmmurali** [Murali-group/GraphSpace#277]
If a graph is shared with a group, there seems to be no away to find that group easily from the page for the graph. It will be useful to add the name(s) of the group(s) to the "Graph Information" or to the area above the tabs that list the owner, graph id, and tags.

**Comment by lohani2280** [comment]
@tmmurali @adbharadwaj This issue has been addressed in the PR https://github.com/Murali-group/GraphSpace/pull/347 . Therefore, I think this can be safely closed.
