### ISSUE TITLE
Search for nodes and edges not working on private graphs

### ISSUE THREAD

**Issue by jlaw9** [Murali-group/GraphSpace#279]
The search for nodes and edges bar (on the graph visualization page) is not doing anything no matter what I try. Seems to be broken.

**Comment by tmmurali** [comment]
@jlaw9 I do not have a problem whether I am logged in or not. Does it
happen only to graphs you own, graphs shared with you, public graphs, or
all of them?

**Comment by jlaw9** [comment]
@tmmurali The search is working on public graphs, but not on private graphs that I own.

**Comment by adbharadwaj** [comment]
Can you send me the url of the graph and the search query you were trying ?

**Comment by adbharadwaj** [comment]
Fixed.
