### ISSUE TITLE
Add new group API not working

### ISSUE THREAD

**Issue by sandeepm96** [Murali-group/GraphSpace#280]
The endpoint for creating a new group of the REST API is not working. Even if a proper JSON body is provided with valid owner_email field, it throws error.

Request body:
![body](https://user-images.githubusercontent.com/15105247/27339624-eb1618ac-55f5-11e7-99d7-d411698ccdfa.png)

Response:
![response](https://user-images.githubusercontent.com/15105247/27339664-ff501732-55f5-11e7-849a-7029852945a2.png)

**Comment by sandeepm96** [comment]
Closing this issue since it turns out that the API endpoint for group creation needs `Content-Type` to be `x-www-form-urlencoded` rather than raw json data.

Request body:
![body](https://user-images.githubusercontent.com/15105247/27344123-e3185338-5602-11e7-9f01-edba0bdfa3e6.png)

Response:
![response](https://user-images.githubusercontent.com/15105247/27344132-eb0a1f0e-5602-11e7-99f1-dc6f48654118.png)

**Comment by tmmurali** [comment]
Should the error message indicate that the Content-Type is incorrect?

Moreover, the error_details point to the wrong docs location. Visiting this
site gives an error.

**Comment by sandeepm96** [comment]
Yes. It would be better if the error message indicates that the content received on the backend is empty and a change in Content-Type might be needed, so that the user can understand that the content is not being sent properly and hence can change Content-Type.

There is no documentation of the GraphSpace API errors. A part of my project involves documenting them and after that we can provide the correct link to the error docs.
