### ISSUE TITLE
PostgreSQL Integrity Error

### ISSUE THREAD

**Issue by mitchwagner** [Murali-group/GraphSpace#283]
I got this error sharing what I think was the first graph created on a new database. Not sure what exactly went wrong, or if it was an issue, but an error popped up in red.

(psycopg2.IntegrityError) duplicate key value violates unique constraint "group_to_graph_pkey" DETAIL: Key (graph_id, group_id)=(1, 1) already exists. [SQL: 'INSERT INTO group_to_graph (graph_id, group_id) VALUES (%(graph_id)s, %(group_id)s)'] [parameters: {'group_id': 1, 'graph_id': 1}]

**Comment by mitchwagner** [comment]
So, I was able to get a similar error when creating a group. I believe it may be caused by clicking a button more than once, and having the action complete the first time while rejecting the action the second time. In other words, various buttons need to be disabled when clicked.

**Comment by adbharadwaj** [comment]
You identified it correctly. I agree we need to disable the submit button
once the form has been submitted.

*Aditya Bharadwaj*
Graduate Research Assistant,
Department of Computer Science,
Virginia Tech
adb@vt.edu

**Comment by adbharadwaj** [comment]
- We need to disable buttons on submit
- Improve the error messages

**Comment by adbharadwaj** [comment]
#323

**Comment by adbharadwaj** [comment]
Closing because its duplicated.
