### ISSUE TITLE
Add a `getting started` documentation for RESTful APIs

### ISSUE THREAD

**Issue by adbharadwaj** [Murali-group/GraphSpace#332]
Migrate documentation from the following blog by @sandeepm96  to GraphSpace documentation.

Blog Link: https://summerofcode17.wordpress.com/2017/05/30/using-the-graphspace-restful-api/

Aim of the documentation is to introduce developers to GraphSpace APIs and explain how to start using our APIs.

**Comment by sanket0211** [comment]
@adbharadwaj  Sir, 
Should I take up this issue? I can take inspiration from @sandeepm96 's blog and create documentation for usage of GraphSpace APIs. 
Thank you.

**Comment by sanket0211** [comment]
@adbharadwaj Sir, 
I have submitted a patch for this issue. https://github.com/Murali-group/GraphSpace/pull/356. Can you please check if its fine. 

Thank you.

**Comment by adbharadwaj** [comment]
@sanket0211 I have commented on it.

**Comment by sanket0211** [comment]
@adbharadwaj Sir,
Need to close this issue. The pull request has been merged by prof. @tmmurali.
