### ISSUE TITLE
Error on trying to start the GraphSpace server

### ISSUE THREAD

**Issue by bruce-wayne99** [Murali-group/GraphSpace#333]
When I am trying to start the GraphSpace server **sqlalchemy.exc.ProgrammingError** occurred.
Please Help.
Screen shots of the error:
![hosting_error](https://user-images.githubusercontent.com/25129274/34919374-c11d2162-f988-11e7-9cd8-28b1ec58dbf5.png)
![hosting_error2](https://user-images.githubusercontent.com/25129274/34919378-d5f80a34-f988-11e7-86de-3f7ac86d2696.png)

**Comment by jlaw9** [comment]
I also get this error when setting up the GraphSpace server locally.  Try running this psql command to to setup the extension, where `username` should be whatever username you setup the database with (in `graphspace/settings/local.py`)
``` sh
sudo -u username psql -c "CREATE EXTENSION pg_trgm;"
```
Then if you get the error `sqlalchemy data type character varying has no default operator class for access method "gin"`, like I did, the suggestion from [here](https://gis.stackexchange.com/a/66178) fixed it for me. You should be able to run their suggestion with something like this:
``` sh
sudo -u username psql -c 'CREATE EXTENSION btree_gin;'
```

**Comment by bruce-wayne99** [comment]
@jlaw9 Thanks for the help!! :)

**Comment by tmmurali** [comment]
@adbharadwaj @jlaw9 Shouldn't these commands be part of the installation instructions? Can an install script run these commands automatically?
