### ISSUE TITLE
Unable to setup graphspace locally

### ISSUE THREAD

**Issue by HitRam** [Murali-group/GraphSpace#335]
I have successfully installed graphspace but when I run it locally it shows - 
"Oops, something went wrong! The GraphSpace administrators have been notified. Sorry for the inconvenience!"

and I get a warning on terminal - 
<img width="1280" alt="screen shot 2018-01-23 at 1 59 32 am" src="https://user-images.githubusercontent.com/19632768/35242990-590007ac-ffe1-11e7-8e97-bcf6d91fc5d7.png">

I am using macOS High Sierra.

**Comment by adbharadwaj** [comment]
It seems to be a server-side error. Can you tell me what is the error message on server-side? You can use debugging tools to debug the response from the server.

**Comment by HitRam** [comment]
@adbharadwaj here is what I get in console

<img width="1280" alt="screen shot 2018-01-24 at 3 53 18 pm" src="https://user-images.githubusercontent.com/19632768/35327130-d095096e-011e-11e8-9b9d-b6d05f053144.png">

**Comment by melvin15may** [comment]
This is not helpful. Can you share the error response (probably a 500 error) from the **Network** tab.

**Comment by HitRam** [comment]
@melvin15may  I was initially using higher version of Django. Later I installed the correct version and it works fine now. But as mentioned #337 , The UI is inconsistent and bower install doesn't help. 
It is unable to load tooltip.js and popover.js 

And while uploading a graph, I get the following error - 

<img width="1280" alt="screen shot 2018-01-28 at 1 58 26 pm" src="https://user-images.githubusercontent.com/19632768/35480410-63d4c8ce-0433-11e8-98c9-06345134e006.png">

**Comment by sagarvijaygupta** [comment]
I am getting the same issue while trying to upload a graph.

**Comment by melvin15may** [comment]
@HitRam Seems to be an elasticsearch issue. Try if you can connect to elasticsearch using `curl localhost:9200`. The [git issue](https://github.com/elastic/elasticsearch-py/issues/63)/[stackoverflow answer](https://stackoverflow.com/a/39447756) regarding this says to re-install elasticsearch and setup correctly. Follow [these](https://github.com/Murali-group/GraphSpace/wiki/Steps-for-setting-up-ElasticSearch-on-AWS) instructions for setup.

**Comment by lohani2280** [comment]
I solved this issue for myself. Yes, its an elasticsearch issue. It took me some time to configure the elasticsearch(earlier my elasticsearch was not configured) and now I can upload the graph successfully. 
@HitRam Please google to how configure elasticsearch.  I found this article quiet useful https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-elasticsearch-on-ubuntu-14-04

**Comment by adbharadwaj** [comment]
@lohani2280 @HitRam @sagarvijaygupta Thanks for collaborating with each other on this. This thread brought an idea to my mind. I think we should start a wiki page where we should document common errors faced while setting up GraphSpace. It would be really helpful. Most of the issues report related to installation are redundant and can be solved with help of a guide which contains solutions to them.

[Common installation roadblocks faced by new contributors
](https://github.com/Murali-group/GraphSpace/wiki/Common-installation-roadblocks-faced-by-new-contributors)

Feel free to edit the following document to your liking. Its for new contributors like you only. Thanks. :)

**Comment by adbharadwaj** [comment]
@HitRam were you able to solve the issue related to popover.js and tooltip.js ?

**Comment by adbharadwaj** [comment]
@HitRam  found the solution. Run the following command to fix the issue. 

```sh
bower install bootstrap#3.3.7
```
The problem was that bootstrap dependency was missing from bower.json file and `bower install bootstrap` command installs bootstrap V4 which doesn't come with plugins like popover.js by default anymore. 

I have fixed this issue by [adding bootstrap dependency with proper version number](https://github.com/Murali-group/GraphSpace/commit/8de44feaff0e182cd24138a522ff1974d1244947).
