### ISSUE TITLE
GraphSpace installation failure: ENORESTARGET No tag found that was able to satisfy ^3.3.7

### ISSUE THREAD

**Issue by guruhegde** [Murali-group/GraphSpace#342]
I tried installing graphspace locally. I have all the dependencies covered.

Installation not complete due to the following error:

bower bower#^3.3.7                           ENORESTARGET No tag found that was able to satisfy ^3.3.7
Additional error details:
No versions found in https://github.com/theshock/atomjs.git

Any clue what is wrong? let me know if you need any further details.

**Comment by guruhegde** [comment]
I got around the problem by modifying version requirement for bower to * (any matching version)

**Comment by jahandaniyal** [comment]
I had faced the same problem while building on 3 different PCs. The resolution was setting bower="*" in the Bower.json file. 
@adbharadwaj I mailed you regarding Build problems on Windows and Ubuntu, and also about issue #336 . I look forward to your suggestions.

**Comment by jahandaniyal** [comment]
I had faced the same problem while building on 3 different PCs. I solved it by setting bower="*" in the Bower.json file.

**Comment by adbharadwaj** [comment]
This shouldn't happen now. I fixed it. It was meant to be bootstrap, not bower.
