### ISSUE TITLE
UI of Export button on Graphs page behaves abnormally

### ISSUE THREAD

**Issue by jahandaniyal** [Murali-group/GraphSpace#343]
This is a minor bug and doesn't affect the functionality of Graphspace in any way. 
**Bug :**  Export button is always at the top because of an unusually high z-index value of 20000. The problem is that when the user wants to sign-out the export button hides the sign-out drop-down menu. Also, while scrolling down, export button goes above the main header of the page. 
I believe the z-index was set to make sure Export Dropdown menu does not get hidden by the Graph Visualisation Canvas. 

**Resolution :** Setting z-index to 1001 fixes the the issue. 

**current div :**
`<div class="btn-group pull-right" style="margin-right: 1em !important; z-index: 20000">`
**proposed change :**
`<div class="btn-group pull-right" style="margin-right: 1em !important; z-index: 1001">`

**Comment by adbharadwaj** [comment]
@jahandaniyal  can you fix this and send a pull request.

**Comment by tmmurali** [comment]
Is there a way to fix this issue without hardcoding a z-index value?

**Comment by adbharadwaj** [comment]
@tmmurali I dont think there is a way to fix it without hardcoding z-index value.

**Comment by tmmurali** [comment]
OK. Thanks.

On Sat, Feb 10, 2018 at 11:06 PM, Aditya Bharadwaj <notifications@github.com
