### ISSUE TITLE
Add GraphSpace documentation link in the README.md

### ISSUE THREAD

**Issue by lohani2280** [Murali-group/GraphSpace#352]
Currently, the README.md file does not contain the documentation link. I think it would be a good idea to add this link http://manual.graphspace.org/en/latest/index.html to our README

**Comment by adbharadwaj** [comment]
Makes sense. Can you send a patch for this as well?

**Comment by tmmurali** [comment]
Add a section to README.md titled "Documentation" with one sentence

"GraphSpace has extensive documentation on the user interface, the REST
API, and a Python package for programmatic interaction."

You can hyperlink each of "user interface" "REST API" and "Python package"
to appropriate portions of docs.graphspace.org

On Mon, Feb 12, 2018 at 11:56 AM, Aditya Bharadwaj <notifications@github.com

**Comment by lohani2280** [comment]
@adbharadwaj @tmmurali  Thanks. I will send the patch for this very soon.

**Comment by lohani2280** [comment]
@adbharadwaj  This issue has been solved in the PR https://github.com/Murali-group/GraphSpace/pull/355 . Therefore, I am closing this issue.

**Comment by adbharadwaj** [comment]
👍
