### ISSUE TITLE
[GSoC 2018] Interested in the project: Implement a machine-readable graph legend interface

### ISSUE THREAD

**Issue by manishkk** [Murali-group/GraphSpace#357]
Hi,
I'm Manish Kumar, a master's student at TU Kaiserslautern, currently writing my thesis at Max Planck Institute for Software Systems in Kaiserslautern, Germany. I have been using Python for quite some time for my academic and hobby projects and also have a fair amount of experience in Django. I have also contributed to Mozilla.  

GraphSpace as a tool seems very interesting to me and I would like to contribute as part of Google Summer of Code 2018. I'm interested in the idea titled 'Implement a machine-readable graph legend interface'. 

Can we have a discussion for further details on the project? Also please give some pointers and suggestions on general things to go through before starting. I'm thinking of working on some beginner friendly bug to get me accustomed to the codebase so it would be great if you can point me to any such issue.

Thank you

@tmmurali @adbharadwaj

**Comment by adbharadwaj** [comment]
@manishkk I am going to close this issue. All non-technical communications should be done using email. We have seen your comment on [NRNB issue 114](https://github.com/nrnb/GoogleSummerOfCode/issues/114). Please go ahead and start working on the patch.
