### ISSUE TITLE
Should edges be selectable?

### ISSUE THREAD

**Issue by annaritz** [Murali-group/GraphSpace#36]
When you click on an edge, it turns red. However, you cannot move the edge.  You must select the nodes and move the nodes.

Further, when you click-and-drag, you will select nodes and some (maybe not all) edges among them.  However, when you move the selected nodes, **all** edges incident on those nodes get moved whether they are selected or not.

The only reason I can think of why we want edges to be selectable is when we click on a SINGLE edge to get the popup information.  Then, the selected edge (in red) corresponds to the content of the popup.

**Comment by adbharadwaj** [comment]
Edges can be selected to view pop up information or edit style in the layout editor. 
Refer to
- http://manual.graphspace.org/en/latest/Viewing_Graphs.html#node-and-edge-popups
- http://manual.graphspace.org/en/latest/Editing_Layouts.html#edit-selected-edges
