### ISSUE TITLE
Add section - Running Graphspace locally on Windows in the README.MD

### ISSUE THREAD

**Issue by jahandaniyal** [Murali-group/GraphSpace#362]
Currently, there are no instructions to build Graphspace locally on windows.
I have tested windows 10 build thoroughly and I think having the option to build on Windows would make it much more flexible.

**Comment by tmmurali** [comment]
Yes, this would be a very useful addition. Can you update README.md with Windows-specific instructions?

Once we merge notifications, installation on all OSes becomes much harder. I think @heidict has successfully installed the notification branch on Windows. @jahandaniyal please coordinate with @heidict on this addition to the README. 

We can update the README.md first for GraphSpace without notifications and then update it on the notifications branch.

**Comment by jahandaniyal** [comment]
@adbharadwaj  Hi, I basically needed these small changes for building locally on windows :

1. To activate the virtual environment I use `venv\Scripts\activate`
2. I start the elastic search service from the installed directory. 
`cd C:\Program Files\Elastic\Elasticsearch\6.2.0\bin` 
`elasticsearch.exe`
Perhaps adding path to ENV_VARIABLE would be good.
3. During installation I manually executed the commands in `install.sh`. I would want to create a .bat file and put these commands in it. 
4. Add a link to windows setup for the ElasticSearch guide.

Other steps were pretty much OS independent.

**Comment by adbharadwaj** [comment]
I think what we can do is create a wiki page for it. @jahandaniyal Can you use this page to document the installation instructions.

https://github.com/Murali-group/GraphSpace/wiki/Installing-GraphSpace-on-Windows-machine

**Comment by jahandaniyal** [comment]
@adbharadwaj I have updated the page. Please have a look!
@lohani2280 Thanks for updating the Documentation info on README.md. I hope you don't mind If I add your changes to this page as well?

**Comment by lohani2280** [comment]
Hey @jahandaniyal  please go on! . There is nothing to mind. Its a very good initiative to create a wiki page and mention the instructions to run GraphSpace locally on Windows.

**Comment by tmmurali** [comment]
@adbharadwaj We should have a master page for installation that contains or links to OS-specific instructions. At the moment, README.md contains info for Linux and Mac OS X while the Windows instructions are on the Wiki. We need to centralise and make all OSes "equal".

README.md is also very long. We should move installation instructions to a separate page.

**Comment by adbharadwaj** [comment]
@tmmurali We probably need to create a table of content on README.md which will link to different pages on wiki. 

I am going to close this issue and initiate a new issue on what should be included on the README page.

https://github.com/Murali-group/GraphSpace/issues/372
