### ISSUE TITLE
Add License and author info in the README.md

### ISSUE THREAD

**Issue by lohani2280** [Murali-group/GraphSpace#363]
Its generally a good practice to include a brief section in the README about the License and author info.Providing licensing and contact information is important to clarify the legal status of the project.Most of the open-source projects follow this practice.While crawling over the web, I came across this famous [gist](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2) which contains a template to make good README.md.

**Comment by mitchwagner** [comment]
We have LICENSE.md for the license component of this issue. You are right that a quick scan over the README, LICENSE, and CONTRIBUTING files do not seem to have contact information in the form of emails. The repository itself does allow users to post issues, but it might be good to have another channel for communication.

**Comment by lohani2280** [comment]
@mitchwagner Yes, I have seen the  LICENSE.md. But what I meant is that we should also add a License  section to the README.md with a small description like "GraphSpace is available under the GNU General Public License v2.0 license. See LICENSE.md for more information" . I have seen many open source projects following this practice and that's why just though to put up my suggestion.

**Comment by tmmurali** [comment]
It is a good idea to add a brief section on the licence to README.md. @lohani2280 please send a patch.

**Comment by adbharadwaj** [comment]
@lohani2280 Don't forget to mention this issue in your pull request. It helps us track which issues have been solved.

**Comment by lohani2280** [comment]
@tmmurali  @adbharadwaj @mitchwagner Thanks for responding. I'll send the patch very soon.
