### ISSUE TITLE
Rename existing graph name

### ISSUE THREAD

**Issue by manishkk** [Murali-group/GraphSpace#365]
In case of duplicate graphs, renaming existing graph name can help us.

**Comment by adbharadwaj** [comment]
Can you explain in detail? I am not sure what the bug or issue is!

**Comment by manishkk** [comment]
@adbharadwaj It's an enhancement. 
In general case also Graph Search should have a feature by which we can rename existing graphs under my graph tab.

Not only in case of duplicate graphs but for giving a meaningful name to existing graph, this feature is required. Suppose I started a graph with graph name "first" but now I want to give some meaningful name to that graph, which is not possible now.


![graph name](https://user-images.githubusercontent.com/3470527/36453698-59d63db2-1699-11e8-99fd-747096da7d23.png)

**Comment by manishkk** [comment]
Similar issue as #317 
so closing this issue.
@adbharadwaj

**Comment by adbharadwaj** [comment]
👍
