### ISSUE TITLE
Login button is invisible in local installation of GraphSpace in Chrome 65.0.3325.162 and Ubuntu 16.0.4.

### ISSUE THREAD

**Issue by JingVT** [Murali-group/GraphSpace#375]
I installed the GraphSpace-2.0 in the Ubuntu 16.0.4 OS. The login button is invisible in Chrome 65.0.3325.162. 
Screenshot:
![local_graphspace_chrome_error](https://user-images.githubusercontent.com/33851894/37618773-aff55c92-2b8d-11e8-8d13-87d4d539395a.png)

The reason is probably GraphSpace is not compatible with the latest version of Chrome. I would like to work on this issue. The idea is removing the duplicate form element. Thanks @adbharadwaj.

**Comment by JingVT** [comment]
The Chrome console is: [DOM] Found 2 elements with non-unique id #register_form: (More info: https://goo.gl/9p2vKq)

**Comment by tmmurali** [comment]
@JingVT please edit the title of the issue as we discussed yesterday.

**Comment by JingVT** [comment]
@tmmurali I did. The current title is the edited one. Is there anything I still need to correct? Thanks.

**Comment by tmmurali** [comment]
Thanks.

**Comment by JingVT** [comment]
The issue can not reproduce.
