### ISSUE TITLE
Unable to upload graph to graphspace locally - Error: add_node() takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by JingVT** [Murali-group/GraphSpace#384]
When I upload the network file to graphspace locally, it shows "Error: add_node() takes exactly 2 arguments (3 given)". And when I upload the network file and style file to graphspace locally, it shows "Error: No JSON object could be decoded". Refer to #335, I re-installed and configured the elasticsearch following https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-elasticsearch-on-ubuntu-14-04, however, the issue is still there.

**Comment by jlaw9** [comment]
@JingVT the add_node() error sounds like a networkx error from graphspace-python which currently uses networkx v1.11. See https://github.com/adbharadwaj/graphspace-python/issues/20 for how to fix that error. 

I'm not sure how to fix the other error you're getting.

**Comment by adbharadwaj** [comment]
Jeff is right. You need to use networkx v1.11. This problem should not
arise if you are using the virtual environment to load python packages. You
need to give more details about the other error. #335
<https://github.com/Murali-group/GraphSpace/issues/335> seems to have a lot
of discussions.

*Aditya Bharadwaj*
Graduate Research Assistant,
Department of Computer Science,
Virginia Tech
adb@vt.edu

**Comment by adbharadwaj** [comment]
Are you using the virtual environment? In any case create a virtual
environment and load python packages from there. What json file are you
uploading ?

A note. I have never encountered this error. You might to debug this.

**Comment by jlaw9** [comment]
Yeah it sounds like whatever JSON file you're trying to upload is formatted incorrectly. Maybe try using a different one?

**Comment by JingVT** [comment]
Thanks @jlaw9. You are right. I think the format of my JSON file was wrong. I create a new one and uploading graph works well now.
