### ISSUE TITLE
The Spring Embedder Layouts for Cytoscape.js v2.7 and v3.2.17 are different

### ISSUE THREAD

**Issue by JingVT** [Murali-group/GraphSpace#404]
After we update Cytoscape.js version #378 from v2.7 to v3.2.17, the "Spring Embedder" layout is different from the old version.

Spring Embedder Layout for Cytoscape.js v2.7
![spring_embedder_2 7](https://user-images.githubusercontent.com/33851894/47526876-18922300-d86f-11e8-81e4-402d958361b1.gif)

Spring Embedder Layout for Cytoscape.js v3.2.17
![spring_embedder_3 7](https://user-images.githubusercontent.com/33851894/47526911-31023d80-d86f-11e8-9c15-8b6e0f7db56e.gif)

**Comment by JingVT** [comment]
The reason could be https://github.com/cytoscape/cytoscape.js/issues/1687

**Comment by adbharadwaj** [comment]
I wouldn't worry too much about. They might have changed some default setting.
