### ISSUE TITLE
Unable to run GraphSpace Locally

### ISSUE THREAD

**Issue by yash170106065** [Murali-group/GraphSpace#418]

**Comment by yash170106065** [comment]
Performing system checks...

System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DEBUG.

System check identified 1 issue (0 silenced).
December 10, 2019 - 13:47:24
Django version 1.9.7, using settings 'graphspace.settings.local'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.



but out comes only at http://127.0.0.1:8000/
Oops, something went wrong! The GraphSpace administrators have been notified. Sorry for the inconvenience!

don't know the issue...
Can anyone help me regarding this....
![Screenshot from 2019-12-11 00-24-44](https://user-images.githubusercontent.com/35887250/70559591-fcedf700-1bac-11ea-92a9-fcc433179e33.png)
![Screenshot from 2019-12-11 00-26-14](https://user-images.githubusercontent.com/35887250/70559592-fd868d80-1bac-11ea-93eb-923153ec2c89.png)

**Comment by yash170106065** [comment]
@adbharadwaj can you help me on this?

**Comment by jahandaniyal** [comment]
@yash170106065 - Can you check console of your browser (F12 for most browsers) for anything specific?

**Comment by yash170106065** [comment]
![Screenshot from 2019-12-11 18-09-50](https://user-images.githubusercontent.com/35887250/70622257-82bb8200-1c41-11ea-949b-7e141cc8d475.png)

**Comment by jahandaniyal** [comment]
Bootstrap seems to be missing. Please check your **bower** installed packages in virtualenv.

**Comment by yash170106065** [comment]
No i already done bower install bootstrap-css

**Comment by adbharadwaj** [comment]
@yash170106065  Can you let me know what is exception message at this location - https://github.com/Murali-group/GraphSpace/blob/master/graphspace/middleware.py#L82

You can use debug mode in PyCharm or simply print the message to find it out.

**Comment by yash170106065** [comment]
Thanks, it's running now
