### ISSUE TITLE
Read-only REST API calls without account

### ISSUE THREAD

**Issue by annaritz** [Murali-group/GraphSpace#43]
Currently, anonymous users cannot use the REST API.  Consider the situation when an anonymous user wants to download all results from a publication (e.g., a bulk download).  Is this an option that should be available for an anonymous user? @tmmurali 

Note that currently all REST API calls require a username and password.

**Comment by adbharadwaj** [comment]
We would want to track the programmatic requests to GraphSpace server. Consider this situation, let's say a user starts downloading a lot of data from GraphSpace server and causes DoS. In such a scenario our easiest defense would be to deny further requests to that user which will impossible if we cannot track the users account back.

Plus this would discourage the users from signing up.

**Comment by adbharadwaj** [comment]
I am closing this issue with a wontfix label so that we revisit the request later.
