### ISSUE TITLE
Not change current view of network when deleting a layout

### ISSUE THREAD

**Issue by ategge** [Murali-group/GraphSpace#77]
Currently, if you want to save a layout with the same name as a previous layout, you need to delete the old layout before saving again. However, when the layout is deleted, and you are currently on the link of that layout, the network returns to a default layout. This is frustrating. Consider the following workflow:
- A user generates a layouts for all the nodes and saves the layout.
- After a little more looking at the data, the user moves a node or two and wants to 'update' the layout.
- When trying to save the current layout with the previous layout name in an effort to update, GS prompts the user to delete the old layout first.
- The user deletes the old layout, and the network then returns to the default layout.
- Now the user has lost not only the 98% good layout, but their preferred layout as well. And the user is frustrated.

Can deleting a layout not affect the current view of the network? Alternatively, may a layout be updated?

**Comment by adbharadwaj** [comment]
This issue will be resolved by allowing users to edit existing layouts #226
