### ISSUE TITLE
Change highlight color of text according to background node color

### ISSUE THREAD

**Issue by ategge** [Murali-group/GraphSpace#79]
I have orange nodes in the example BPN network. When I click a node, the text turns red. The combination of the orange and red makes the text illegible. If the highlight color could be adjusted based on the background node color, then the text would be readable.

user2 has this network as an example: http://ec2-52-5-177-0.compute-1.amazonaws.com/graphs/user2%40example.com/BPN-network-liver-signaling/

PS: I could only hit nitpicking once, this is such a minor issue at this point in time.

**Comment by adbharadwaj** [comment]
The highlight color has been changed. Details are available [here](http://manual.graphspace.org/en/latest/Viewing_Graphs.html#highlighted-graph-elements).
