### ISSUE TITLE
Copy layouts to other graphs

### ISSUE THREAD

**Issue by ategge** [Murali-group/GraphSpace#84]
I have been uploading the same graph with different visual styles (colors, shapes, node labels) but all nodes still having the same id in each graph. Currently, the only way to preserve the same layout is to reupload the different versions of the graph to the same graphid in which a layout is saved and export the image. It would be convenient if a user could copy a layout (how? I am not sure) and have the same layout for multiple graph ids.

**Comment by adbharadwaj** [comment]
Users can now export [network stylesheet](http://manual.graphspace.org/en/latest/Interacting_with_Graphs.html#export) which is basically exportable layout of the graph. This layout stylesheet JSON file can be imported while uploading the graph or in the layout editor.
