### ISSUE TITLE
Reduce the spacing of the sidebar tabs on right of screen

### ISSUE THREAD

**Issue by ategge** [Murali-group/GraphSpace#85]
I find myself doing a lot of scrolling to navigate the tabs on the right of the screen. Initially, the sidebar starts with layouts, (optionally k-step), and search tabs already open. In addition, there is a lot of white space between each of the tabs. Is there any way to consolidate this section so that a user does not have to scroll through as many tabs? A user may not even know about the k-step filter option because it is out of the visible screen. Maybe at first, only have the graph details open and everything else closed? That way a user will be aware of all the tabs available to select from.

**Comment by adbharadwaj** [comment]
This is not relevant in GraphSpace 2.0. The UI has changed completely.
